AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CI CD Demo APP
Resources:
  CICDDemoApp:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.amazonaws.lambda.teamdemo.LambdaFunctionHandler::handleRequest
      Runtime: java8
      CodeUri: target/teamdemo-1.0.0.jar
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::766377766697:role/babu_cicddemo'
      Events:
        getTeamAPI:
          Type: Api
          Properties:
            Path: /getTeam
            Method: get
      Environment:
        Variables:
          REGION: us-east-1